version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./videos:/app/videos
    environment:
      - CONFIG_PATH=/app/config.json

    networks:
      - my_network

   

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Пароль для администратора Grafana (можно изменить)
    depends_on:
      - prometheus
    networks:
      - my_network

volumes:
  grafana_data:

networks:
  my_network:
    driver: bridge
